apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "whatsapp-reader.fullname" . }}-api
  labels:
    {{- include "whatsapp-reader.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  {{- if not .Values.api.autoscaling.enabled }}
  replicas: {{ .Values.api.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "whatsapp-reader.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: api
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        checksum/secret: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
      labels:
        {{- include "whatsapp-reader.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: api
    spec:
      {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "whatsapp-reader.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
      - name: api
        securityContext:
          {{- toYaml .Values.securityContext | nindent 12 }}
        image: "{{ .Values.api.image.repository }}:{{ .Values.api.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.api.image.pullPolicy }}
        ports:
        - name: http
          containerPort: {{ .Values.api.service.targetPort }}
          protocol: TCP
        env:
        {{- range .Values.api.env }}
        - name: {{ .name }}
          value: {{ .value | quote }}
        {{- end }}
        {{- range .Values.api.secrets }}
        - name: {{ .name }}
          valueFrom:
            secretKeyRef:
              name: {{ $.Values.secrets.api.name }}
              key: {{ .key }}
        {{- end }}
        livenessProbe:
          {{- toYaml .Values.api.livenessProbe | nindent 12 }}
        readinessProbe:
          {{- toYaml .Values.api.readinessProbe | nindent 12 }}
        resources:
          {{- toYaml .Values.api.resources | nindent 12 }}
        volumeMounts:
        {{- if .Values.persistence.uploads.enabled }}
        - name: uploads
          mountPath: {{ .Values.persistence.uploads.mountPath }}
        {{- end }}
        {{- if .Values.persistence.exports.enabled }}
        - name: exports
          mountPath: {{ .Values.persistence.exports.mountPath }}
        {{- end }}
      volumes:
      {{- if .Values.persistence.uploads.enabled }}
      - name: uploads
        persistentVolumeClaim:
          claimName: {{ include "whatsapp-reader.fullname" . }}-uploads
      {{- end }}
      {{- if .Values.persistence.exports.enabled }}
      - name: exports
        persistentVolumeClaim:
          claimName: {{ include "whatsapp-reader.fullname" . }}-exports
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}